# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/podparser',
                'doc_host': 'https://snwbl.github.io',
                'git_url': 'https://github.com/snwbl/podparser',
                'lib_path': 'podparser'},
  'syms': {'podparser.core': {'podparser.core.foo': ('core.html#foo', 'podparser/core.py')}}}
